### ISSUE TITLE
A mistake in Crawler_16personalities.py that may take severe problems

### ISSUE THREAD

**Issue by Neph0s** [Kali-Hac/ChatGPT-MBTI#2]
the code
`if sess_r.json()['user']['traits']['mind'] != 'Extraverted':
            mind_value = 100 - (101 + scores[0]) // 2
        else:
            mind_value = (101 + scores[0]) // 2
        if sess_r.json()['user']['traits']['energy'] != 'Intuitive':
            energy_value = 100 - (101 + scores[1]) // 2
        else:
            energy_value = (101 + scores[1]) // 2`

should be modified as:

`if sess_r.json()['user']['traits']['energy'] != 'Extraverted':
        energy_value = 100 - (101 + scores[0]) // 2
        ans1 += 'I'
    else:
        energy_value = (101 + scores[0]) // 2
        ans1 += 'E'
    if sess_r.json()['user']['traits']['mind'] != 'Intuitive':
        mind_value = 100 - (101 + scores[1]) // 2
        ans1 += 'S'`
        
cuz 'mind' does not correspond to E, and corresponds to N/S instead, as can be evidenced by 

> sess_r.json()['user']['traits']
{'energy': 'Extraverted', 'mind': 'Intuitive', 'nature': 'Thinking', 'tactics': 'Judging', 'identity': 'Assertive'}  

Hence, (sess_r.json()['user']['traits']['mind'] != 'Extraverted') and (sess_r.json()['user']['traits']['energy'] != 'Intuitive') are both always True.

**Comment by Kali-Hac** [comment]
Thanks for your answer and sorry for the mistake. We have updated our code.

Since we directly use the official result “print('Character:', sess_r.json()['user']['avatarFull'].split('avatars/')[1].split('.')[0])”, this code does not influence the results of the final personality role prediction  And it also does not affect the final evaluation result (consistency, robustness, and fairness scores) in our paper, as we regard each score as an independent dimension. Unfortunately, it may change the personality scores in the first and second dimensions, and we will revise this in the future.
